name: Build All Flake Outputs & Push to Cachix
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('flake.lock') }}
          restore-prefixes-first-match: |
            nix-${{ runner.os }}-
      - uses: cachix/cachix-action@v12
        with:
          name: mrjones2014-dotfiles
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build all configurations
        run: |
          nix develop .#ci --command nix-fast-build --skip-cached --no-nom --systems x86_64-linux,aarch64-darwin
          # track how much disk space the action uses
          df -h
