name: Build All Flake Outputs & Push to Cachix
on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-nixos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config: [homelab, tower, nixbook]
    steps:
      - uses: actions/checkout@v4
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          df -h
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-${{ matrix.config }}-${{ hashFiles('flake.lock') }}
          restore-prefixes-first-match: |
            nix-${{ runner.os }}-${{ matrix.config }}-
            nix-${{ runner.os }}-
      - uses: cachix/cachix-action@v12
        with:
          name: your-cache-name
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build configuration
        run: nix build .#nixosConfigurations.${{ matrix.config }}.config.system.build.toplevel

  build-darwin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc
          df -h
      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: nix-community/cache-nix-action@v5
        with:
          primary-key: nix-${{ runner.os }}-darwin-${{ hashFiles('flake.lock') }}
          restore-prefixes-first-match: |
            nix-${{ runner.os }}-darwin-
            nix-${{ runner.os }}-
      - uses: cachix/cachix-action@v12
        with:
          name: your-cache-name
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build Darwin configuration
        run: nix build .#darwinConfigurations.darwin.system
