name: Check Nix flake
on:
  pull_request:
  push:
    branches:
      - master
  workflow_dispatch: # allow manual trigger
jobs:
  check-flake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: mrjones2014-dotfiles
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Run nix flake check
        run: nix flake check
