name: "Build and Cache"
on:
  pull_request:
  push:
    branches-ignore:
      # ignore automated update branches, rely on pull_request hook
      - 'automation/**'
      - 'dependabot/**'
jobs:
  tests-pass:
    name: all systems go
    runs-on: ubuntu-latest
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - run: exit 1
    needs:
      - tests

  tests:
    strategy:
      # Allow other jobs to finish building and cache properly before bailing
      fail-fast: false
      matrix:
        include:
          - os: macos-15 # for macOS home-manager
          - os: ubuntu-latest
            system: "x86_64-linux"

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v30
      with:
        extra_nix_config: |
          extra-platforms = ${{ matrix.extraPlatforms }}

    - uses: cachix/cachix-action@v15
      with:
        name: mrjones2014-dotfiles
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: build all definitions
      run: nix run github:Mic92/nix-fast-build -L -- --skip-cached --no-download --no-nom --eval-workers 1 --eval-max-memory-size 2048 --flake .#checks.${{ matrix.system }}
