name: Update flake dependencies

on:
  schedule:
    - cron: '0 16 * * 5'
  workflow_dispatch: # for allowing manual triggers of the workflow

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: update flake.lock
      run: nix flake update
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: "flake: update dependencies"
        title: "[automation] update flake dependencies"
        branch: "automation/update-flake-dependencies"
        token: ${{ secrets.UPDATE_FLAKE_TOKEN }}
    - name: Ping me in a comment on the PR
      run: |
        PR_NUMBER=${{ github.event.pull_request.number }}
        COMMENT="Ping @mrjones2014"
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
        COMMENT_URL="https://api.github.com/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"
        curl -s -H "Authorization: token ${GITHUB_TOKEN}" -X POST $COMMENT_URL -d "{\"body\":\"$COMMENT\"}"
